[ores]
	#The retrogeneration key. Basically IE checks if this key is saved in the chunks data. If it isn't, it will perform retrogen on all ores marked for retrogen.
	#Change this in combination with the retrogen booleans to regen only some of the ores.
	retrogen_key = "DEFAULT"
	#Set this to false to disable the logging of the chunks that were flagged for retrogen.
	retrogen_log_flagChunk = true
	#Set this to false to disable the logging of the chunks that are still left to retrogen.
	retrogen_log_remaining = true

	#Ore generation config - copper
	[ores.copper]
		#The maximum size of a vein. Set to 0 to disable generation
		#Range: > 0
		vein_size = 0
		#The minimum Y coordinate this ore can spawn at
		#Range: > -2147483648
		min_y = 40
		#The maximum Y coordinate this ore can spawn at
		#Range: > -2147483648
		max_y = 72
		#The average number of veins per chunk
		#Range: > 0
		avg_veins_per_chunk = 8
		#Set this to true to allow retro-generation of copper Ore.
		retrogen_enable = false

	#Ore generation config - bauxite
	[ores.bauxite]
		#The maximum size of a vein. Set to 0 to disable generation
		#Range: > 0
		vein_size = 0
		#The minimum Y coordinate this ore can spawn at
		#Range: > -2147483648
		min_y = 40
		#The maximum Y coordinate this ore can spawn at
		#Range: > -2147483648
		max_y = 85
		#The average number of veins per chunk
		#Range: > 0
		avg_veins_per_chunk = 8
		#Set this to true to allow retro-generation of bauxite Ore.
		retrogen_enable = false

	#Ore generation config - lead
	[ores.lead]
		#The maximum size of a vein. Set to 0 to disable generation
		#Range: > 0
		vein_size = 0
		#The minimum Y coordinate this ore can spawn at
		#Range: > -2147483648
		min_y = 8
		#The maximum Y coordinate this ore can spawn at
		#Range: > -2147483648
		max_y = 36
		#The average number of veins per chunk
		#Range: > 0
		avg_veins_per_chunk = 4
		#Set this to true to allow retro-generation of lead Ore.
		retrogen_enable = false

	#Ore generation config - silver
	[ores.silver]
		#The maximum size of a vein. Set to 0 to disable generation
		#Range: > 0
		vein_size = 0
		#The minimum Y coordinate this ore can spawn at
		#Range: > -2147483648
		min_y = 8
		#The maximum Y coordinate this ore can spawn at
		#Range: > -2147483648
		max_y = 40
		#The average number of veins per chunk
		#Range: > 0
		avg_veins_per_chunk = 4
		#Set this to true to allow retro-generation of silver Ore.
		retrogen_enable = false

	#Ore generation config - nickel
	[ores.nickel]
		#The maximum size of a vein. Set to 0 to disable generation
		#Range: > 0
		vein_size = 0
		#The minimum Y coordinate this ore can spawn at
		#Range: > -2147483648
		min_y = 8
		#The maximum Y coordinate this ore can spawn at
		#Range: > -2147483648
		max_y = 24
		#The average number of veins per chunk
		#Range: > 0
		avg_veins_per_chunk = 2
		#Set this to true to allow retro-generation of nickel Ore.
		retrogen_enable = false

	#Ore generation config - uranium
	[ores.uranium]
		#The maximum size of a vein. Set to 0 to disable generation
		#Range: > 0
		vein_size = 0
		#The minimum Y coordinate this ore can spawn at
		#Range: > -2147483648
		min_y = 8
		#The maximum Y coordinate this ore can spawn at
		#Range: > -2147483648
		max_y = 24
		#The average number of veins per chunk
		#Range: > 0
		avg_veins_per_chunk = 2
		#Set this to true to allow retro-generation of uranium Ore.
		retrogen_enable = false
