["World Generation"]
	#Set to FALSE to prevent 'Thermal Series' Apatite from generating.
	Apatite = false
	#Set to FALSE to prevent 'Thermal Series' Cinnabar from generating.
	Cinnabar = false
	#Set to FALSE to prevent 'Thermal Series' Niter from generating.
	Niter = false
	#Set to FALSE to prevent 'Thermal Series' Sulfur from generating.
	Sulfur = false
	#Set to FALSE to prevent 'Thermal Series' Copper from generating.
	Copper = false
	#Set to FALSE to prevent 'Thermal Series' Tin from generating.
	Tin = false
	#Set to FALSE to prevent 'Thermal Series' Lead from generating.
	Lead = false
	#Set to FALSE to prevent 'Thermal Series' Silver from generating.
	Silver = false
	#Set to FALSE to prevent 'Thermal Series' Nickel from generating.
	Nickel = false
	#Set to FALSE to prevent 'Thermal Series' Oil Sands from generating.
	Oil = false


